name: Build and Test React Web Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Installing Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Installing NPM packages
        run: npm ci

      - name: Linting code
        run: npm run lint

      - name: Running tests
        run: npm run test

      - name: Building project
        run: npm run build

  push_to_docker_hub:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_TOKEN }}"

      - name: Build Docker image
        run: docker build -t react-web-app .

      - name: Tag Docker image
        run: docker tag react-web-app ${{ secrets.DOCKER_USERNAME }}/react-web-app

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/react-web-app
